# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55a992cd37d22b2e6818c1ecd845b65345262b83d7539514048a901efd1971c7744a0b596c95f170b1684968fef91788560db47be0037c06ada0f4412961d3e1

test:
  secret_key_base: 90bc4a4973b99ed5e9587a388c8e8e444c836fde998ef5cad0418b67801cbeda49336b5c697e1906ebd39b633c6d659f7354f174da5ff651a36e0dde325d816b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
